# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 971e2177e70666ca819514f6239bdcfe622ed5ee82e1e86e84d27155bd00f91029f785b3cef7d4ee745e2a19d80903eb2aeb6153388c65c26c2742618d98d0b1

test:
  secret_key_base: 7454a50b4ce9ee58205897c627c2cb7a502c788e877e71f335734716286036654805a002ad1ca78692b7af34f3fafbfe33147591c4c5f5aa516105183fddd09a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
